version: "3.2"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - "E:/Projects/MongoDB/Data:/var/lib/mongodb"
    ports:
      - 27017:27017
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    restart: always
    ports:
      - "8000:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - /recidex-server/node_modules
      - ./server:/recidex-server
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    volumes:
      - /recidex-client/node_modules
      - ./web-client:/recidex-client
    env_file:
      - ./web-client/.env
    restart: unless-stopped
    depends_on:
      - "api"
