version: "3.2"
services:
  mongodb:
      container_name: recidex_mongo
      image: mongo
      restart: unless-stopped
      volumes:
        - ./db:/data/db
      ports:
        - "27017:27017"
  api:
      container_name: recidex-api
      image: yotamgolan.com:5000/recidex_api
      build:
        context: ./server
        dockerfile: Dockerfile
        args:
          npm_flag: "--omit=dev"
          start_script: "start"
      restart: unless-stopped
      depends_on:
        - mongodb
  client:
      container_name: recidex_client
      image: yotamgolan.com:5000/recidex_client
      build: ./web-client
      depends_on:
        - api
      restart: unless-stopped
      ports:
        - "8080:80"


