version: "3.2"
services:
  mongodb:
      image: mongo
      restart: unless-stopped
      volumes:
        - ./db:/data/db
      ports:
        - "27017:27017"
  api:
      build:
        context: ./server
        dockerfile: Dockerfile
        args:
          npm_flag: "--omit=dev"
          start_script: "start"
      restart: unless-stopped
      env_file:
        - ./server/.env
      depends_on:
        - mongodb
  client:
      build: ./web-client
      depends_on:
        - api
      restart: unless-stopped
      ports:
        - "8080:80"
      env_file:
      - ./web-client/.env


