version: "3.2"
services:
  mongodb:
      container_name: recidex_mongo
      image: mongo:4.4
      restart: unless-stopped
      volumes:
        - ./db:/data/db
        - ./db_backups:/db_backups
  api:
      container_name: recidex_api
      image: localhost:5000/recidex_api
      restart: unless-stopped
      depends_on:
        - mongodb
  client:
      container_name: recidex_client
      image: localhost:5000/recidex_client
      depends_on:
        - api
      restart: unless-stopped
      ports:
        - "127.0.0.1:8080:80"


