version: "3.2"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - /recidex-server/node_modules
      - ./server:/recidex-server
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    restart: always
    ports:
      - "8080:80"
