version: "3.2"
services:
  mongodb:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  api:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/recidex-server
      - nodemodules:/recidex-server/node_modules
    depends_on:
      - mongodb
volumes:
    nodemodules: