version: "3.2"
services:
  api:
      image: yotamgolan.com:5000/recidex_api
      build:
        context: ./server
        dockerfile: Dockerfile
        args:
          npm_flag: "--omit=dev"
          start_script: "start"
  client:
      image: yotamgolan.com:5000/recidex_client
      build: ./web-client

