version: "3.2"
services:
  mongodb:
      container_name: recidex_mongo
      image: mongo:3.6.8
      restart: unless-stopped
      volumes:
        - ./db:/data/db
      ports:
        - "27017:27017"
  api:
      container_name: recidex_api
      image: localhost:5000/recidex_api
      restart: unless-stopped
      depends_on:
        - mongodb
  client:
      container_name: recidex_client
      image: localhost:5000/recidex_client
      depends_on:
        - api
      restart: unless-stopped
      ports:
        - "8080:80"


