FROM node:alpine as build-deps
WORKDIR /recidex-client
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-deps /recidex-client/build /var/www/recidex-client

